FROM node:15.0.0-alpine
WORKDIR /app
COPY ./package.json ./
RUN apk add --no-cache git
RUN apk add --no-cache --virtual .build-deps alpine-sdk python2
# RUN apk --no-cache add --virtual native-deps \
#   g++ gcc libgcc libstdc++ linux-headers make python && \
#   npm install --quiet node-gyp -g &&\
#   npm install --quiet && \
#   apk del native-deps
RUN yarn
RUN npm rebuild node-sass
COPY ./ ./


EXPOSE 3000

CMD ["yarn", "start"]