FROM node:10.18.1-alpine3.11 AS BUILD
WORKDIR /app
COPY ./package.json ./
RUN yarn
COPY ./ ./
RUN yarn build

FROM nginx:1.18.0-alpine AS SERVE
RUN rm -R /usr/share/nginx/html
COPY --from=BUILD /app/build/ /usr/share/nginx/html/beta
ADD ./prod-nginx-default.conf /etc/nginx/conf.d/default.conf
