version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: yarn build
  web_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CI=true
    command: yarn test
  # web_old:
  #   build:
  #     context: $PWD/../das-web
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - /app/client/bower_components
  #     - $PWD/../das-web:/app
  #   command: yarn docker_start
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - "web"
      # - "web_old"
    ports:
      - '9000:80'
      - '35729:35729'