version: '3'
services:
  web_api:
    build:
      context: ./das-web-proxy
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./das-web-proxy:/app
  # mock_api:
  #   build:
  #     context: ./mock-api
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - ./mock-api:/app
  web_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: yarn test
    restart: on-failure
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - "web"
      - "web_api"
      # - "mock_api"
    ports:
      - '9000:80'
      - '35729:35729'