version: '3'
services:
  web_api:
    build:
      context: ./das-web-api
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./das-web-api:/app
      - ~/.config/gcloud/web_api_credentials.json:/gcp/creds.json
    environment:
      - PORT=3030
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
  # mock_api:
  #   build:
  #     context: ./mock-api
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - ./mock-api:/app
  web: &web
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
  web_test:
    <<: *web
    command: yarn test
    restart: on-failure
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - "web"
      - "web_api"
      # - "mock_api"
    ports:
      - '9000:80'
      - '35729:35729'
volumes:
   mongo-data: