export const CHOICE_LIST_ELEMENT_CHOICE_MY_DATA_TYPE = {
  EVENT_TYPES_FROM_EVENT_CATEGORY: 'EVENT_TYPES_FROM_EVENT_CATEGORY',
  FEATURES_FROM_FEATURE_CATEGORY: 'FEATURES_FROM_FEATURE_CATEGORY',
  SOURCES: 'SOURCES',
  SUBJECTS_FROM_SUBJECT_GROUP: 'SUBJECTS_FROM_SUBJECT_GROUP',
  SUBJECTS_FROM_SUBJECT_SUBTYPE: 'SUBJECTS_FROM_SUBJECT_SUBTYPE',
  USERS: 'USERS',
};

export const CHOICE_LIST_ELEMENT_CHOICE_TYPES = {
  EXISTING_CHOICE_LIST: 'EXISTING_CHOICE_LIST',
  MY_DATA: 'MY_DATA',
};

export const CHOICE_LIST_ELEMENT_INPUT_TYPES = {
  DROPDOWN: 'DROPDOWN',
  LIST: 'LIST',
};

export const DATE_TIME_ELEMENT_INPUT_TYPES = {
  DATE_TIME: 'DATE_TIME',
  DATE: 'DATE',
  TIME: 'TIME',
};

export const FORM_ELEMENT_LOGIC_CONDITION_OPERATORS = {
  INPUT_IS_EXACTLY: 'INPUT_IS_EXACTLY',
  HAS_INPUT: 'HAS_INPUT',
  DOES_NOT_HAVE_INPUT: 'DOES_NOT_HAVE_INPUT',
  CONTAINS: 'CONTAINS',
  IS_CONTAINED_BY: 'IS_CONTAINED_BY',
  IS_NOT_CONTAINED_BY: 'IS_NOT_CONTAINED_BY',
};

export const FORM_ELEMENT_TYPES = {
  ATTACHMENT: 'ATTACHMENT',
  CHOICE_LIST: 'CHOICE_LIST',
  COLLECTION: 'COLLECTION',
  DATE_TIME: 'DATE_TIME',
  HEADER: 'HEADER',
  LOCATION: 'LOCATION',
  NUMERIC: 'NUMERIC',
  SECTION: 'SECTION',
  TEXT: 'TEXT',
};

export const HEADER_ELEMENT_SIZES = {
  LARGE: 'LARGE',
  MEDIUM: 'MEDIUM',
  SMALL: 'SMALL',
};

export const ROOT_CANVAS_ID = 'root';

export const TEXT_ELEMENT_INPUT_TYPES = {
  SHORT: 'SHORT_TEXT',
  LONG: 'LONG_TEXT',
};
