version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    restart: on-failure