version: 2.1
commands:
  configure_git_for_commit_and_push:
    steps:
      - run: 'git config user.email "circleci@vulcan.com"'
      - run: 'git config user.name "circleci"'
      - run: 'git config push.default current'
      - add_ssh_keys:
          fingerprints:
            - 'c9:1d:33:93:16:c9:28:1c:3c:f4:f0:85:e3:f0:f8:d7'
  activate_google_service_account:
    steps:
      - run: 'gcloud auth activate-service-account --key-file=<(echo "$ENCODED_GCR_KEY" | base64 --decode)'
  docker_login:
    steps:
      - run: 'echo "$ENCODED_GCR_KEY" | base64 --decode | docker login --username _json_key --password-stdin https://gcr.io'
executors:
  gcloud:
    docker:
      - image: 'google/cloud-sdk:269.0.0'
jobs:
  build_das_web_react:
    executor: 'gcloud'
    steps:
      - 'setup_remote_docker'
      - 'docker_login'
      - 'checkout'
      - run: 'make build_and_push descriptive_gcr_path_stem="$CIRCLE_BRANCH" unique_gcr_tag="$CIRCLE_WORKFLOW_ID"'
      - 'configure_git_for_commit_and_push'
      - 'activate_google_service_account'
      - run: 'make commit_and_push_manifest descriptive_gcr_path_stem="$CIRCLE_BRANCH" unique_gcr_tag="$CIRCLE_WORKFLOW_ID"'
workflows:
  version: 2
  docker_build_workflow:
    jobs:
      - 'build_das_web_react'
