FROM node:lts
WORKDIR /app
RUN npm i json-server -g
COPY ./package.json ./
RUN yarn
COPY ./ ./

EXPOSE 8080

CMD ["json-server", "--watch", "index.js", "--host", "0.0.0.0", "--port", "8080", "--routes", "routes.json"]
