import { animalControlTypeV2, fireTypeV2, snareTypeV1, spoorTypeV1 } from '../../__test-helpers/fixtures/event-types';
import { mapEventTypesToCategories } from './';
import { monitoringCategory, securityCategory } from '../../__test-helpers/fixtures/event-categories';

describe('Utils - Event types', () => {
  describe('mapEventTypesToCategories', () => {
    const eventCategories = { monitoring: monitoringCategory, security: securityCategory };
    const eventTypes = [
      { ...animalControlTypeV2, version: 2 },
      { ...fireTypeV2, version: 2 },
      { ...snareTypeV1, version: 1 },
      { ...spoorTypeV1, version: 1 },
    ];

    test('maps the event types in visible categories sorting the event types and the categories by the ordernum', () => {
      expect(mapEventTypesToCategories(eventTypes, eventCategories)).toEqual([{
        display: 'Monitoring',
        flag: 'user',
        id: 'e31f75e3-d86d-4e20-b397-5bb9fe46c5cf',
        is_active: true,
        ordernum: 1,
        permissions: ['create', 'update', 'read', 'delete'],
        types: [{
          auto_resolve: false,
          category: 'monitoring',
          default_priority: 300,
          default_state: 'active',
          display: 'Fire v2',
          geometry_type: 'Polygon',
          has_events_assigned: true,
          icon: 'fire_rep',
          icon_id: 'fire_rep',
          id: 'bbd64930-a029-4d89-98f2-f94e269f8fe6',
          is_active: true,
          is_collection: false,
          ordernum: 2,
          resolve_time: null,
          url: 'https://stage.pamdas.org/api/v2.0/activity/eventtypes/fire_v2',
          value: 'fire_v2',
          version: 2,
        }],
        value: 'monitoring',
      }, {
        display: 'Security',
        flag: 'user',
        id: '007a45d3-2aba-4ed1-b3fc-e09fc0ad41f8',
        is_active: true,
        ordernum: 58,
        permissions: ['create', 'update', 'read', 'delete'],
        types: [{
          auto_resolve: false,
          category: 'security',
          default_priority: 0,
          default_state: 'active',
          display: 'Animal Control v2',
          geometry_type: 'Point',
          has_events_assigned: true,
          icon: 'animal_control_rep',
          icon_id: 'animal_control_rep',
          id: '29736bf4-c1eb-4cb7-bdb2-3b6464108517',
          is_active: true,
          is_collection: false,
          ordernum: 1,
          resolve_time: null,
          url: 'https://stage.pamdas.org/api/v2.0/activity/eventtypes/animal_control_v2',
          value: 'animal_control_v2',
          version: 2,
        }, {
          auto_resolve: false,
          category: {
            display: 'Security',
            flag: 'user',
            id: '007a45d3-2aba-4ed1-b3fc-e09fc0ad41f8',
            is_active: true,
            ordernum: 856,
            permissions: ['create', 'update', 'delete', 'read'],
            value: 'security',
          },
          default_priority: 0,
          default_state: 'new',
          display: 'Snare',
          geometry_type: 'Point',
          has_events_assigned: true,
          icon: null,
          icon_id: 'snare_rep',
          id: '8e2812d8-4ac9-4874-b1b2-1adc5ea192b5',
          is_active: true,
          is_collection: false,
          ordernum: 800,
          resolve_time: null,
          url: 'https://root.dev.pamdas.org/api/v1.0/activity/events/eventtypes/8e2812d8-4ac9-4874-b1b2-1adc5ea192b5',
          value: 'snare_rep',
          version: 1,
        }, {
          auto_resolve: false,
          category: {
            display: 'Security',
            flag: 'user',
            id: '007a45d3-2aba-4ed1-b3fc-e09fc0ad41f8',
            is_active: true,
            ordernum: 856,
            permissions: ['create', 'update', 'delete', 'read'],
            value: 'security',
          },
          default_priority: 0,
          default_state: 'new',
          display: 'Spoor',
          geometry_type: 'Point',
          has_events_assigned: false,
          icon: null,
          icon_id: 'spoor_rep',
          id: '58bde7d9-4a5c-43bf-a5c7-06803a3aaec8',
          is_active: true,
          is_collection: false,
          ordernum: 802,
          resolve_time: null,
          url: 'https://root.dev.pamdas.org/api/v1.0/activity/events/eventtypes/58bde7d9-4a5c-43bf-a5c7-06803a3aaec8',
          value: 'spoor_rep',
          version: 1,
        }],
        value: 'security',
      }]);
    });
  });
});
