export const DATE_TIME_ELEMENT_INPUT_TYPES = {
  DATE_TIME: 'DATE_TIME',
  DATE: 'DATE',
  TIME: 'TIME',
};

export const FORM_ELEMENT_TYPES = {
  ATTACHMENT: 'ATTACHMENT',
  CHOICE_LIST: 'CHOICE_LIST',
  COLLECTION: 'COLLECTION',
  DATE_TIME: 'DATE_TIME',
  HEADER: 'HEADER',
  LOCATION: 'LOCATION',
  NUMERIC: 'NUMERIC',
  SECTION: 'SECTION',
  TEXT: 'TEXT',
};

export const ROOT_CANVAS_ID = 'root';
