name: ArgoCD Update Image (internal)

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      app-subdir:
        type: string
        default: ""
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      ARGOCD_APPS_SSH_KEY:
        required: true

jobs:
  update:
    uses: PADAS/serca-pipelines/.github/workflows/_argocd-update-image.yml@main
    with:
      app-name: ${{ inputs.app-name }}
      app-subdir: ${{ inputs.app-subdir }}
      environment: ${{ inputs.environment }}
      image-tag: ${{ inputs.image-tag }}
    secrets:
      ARGOCD_APPS_SSH_KEY: ${{ secrets.ARGOCD_APPS_SSH_KEY }}
