name: Build das-web-react
on:
  push:
    branches:
      - develop
      - 'release-**'

jobs:
  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v1-stable
    with:
      environment: padas-app
      repository: europe-west3-docker.pkg.dev/padas-app/er-mt/das-web-react
      tag: ${{ github.head_ref || github.ref_name }}-${{ github.run_number }}
      dockerfile: Dockerfile.mt
