name: Build das-web-react
on:
  push:
    branches:
      - develop
      - 'release-**'

jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          npm pkg set "buildbranch"="${{ github.head_ref || github.ref_name }}"
          npm pkg set "buildnum"="${{ github.run_number }}"
      - uses: actions/upload-artifact@v4
        with:
          name: npm-config
          path: package.json
  build:
    needs: config
    uses: ./.github/workflows/_build_docker.yml
    with:
      environment: padas-app
      repository: europe-west3-docker.pkg.dev/padas-app/er-mt/das-web-react
      tag: ${{ github.head_ref || github.ref_name }}-${{ github.run_number }}
      dockerfile: Dockerfile.mt
      artifact-download: true
      artifact-name: npm-config
