name: Build das-server on Pull Request
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - reopened

jobs:
  config:
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    outputs:
      build-args: ${{ steps.env-vars.outputs.build-args }}
    environment: 
      name: ${{ github.head_ref }}
      url: "https://${{ github.head_ref }}.dev.pamdas.org"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          npm pkg set "buildbranch"="${{ github.event.pull_request.head.sha }}"
          npm pkg set "buildnum"="${{ github.run_number }}"
      - uses: actions/upload-artifact@v4
        with:
          name: npm-config
          path: package.json
      - name: Read env file
        id: env-vars
        if: github.ref_name == 'develop'
        run: |
          tracking_id=$(grep REACT_APP_GA4_TRACKING_ID .env.development | cut -d '=' -f2)
          echo "build-args=REACT_APP_GA4_TRACKING_ID=$tracking_id" >> $GITHUB_OUTPUT

  build:
    run: echo "Labels debug: ${{ toJson(github.event.pull_request.labels) }}"
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    needs: config
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@main
    with:
      environment: padas-app
      repository: europe-west3-docker.pkg.dev/padas-app/er-mt/das-web-react
      tag: ${{ github.event.pull_request.head.sha }}
      dockerfile: Dockerfile.mt
      artifact-download: true
      artifact-name: npm-config
      build-args: ${{ needs.config.outputs.build-args || '' }}
